---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/2rgu_screenshot/2rgu_screenshot.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/74776/articles/356680/master/file/figures/2rgu_screenshot/2rgu_screenshot.png"
